spring:
  config:
    import: configserver:http://localhost:9297
  mail:
    host: smtp.xxx.com
    port: 587
    username: xxx@gmail.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true