CREATE TABLE client (
    id BIGINT generated by default as identity primary key,
    username varchar(255) not null UNIQUE,
    email varchar(255) not null UNIQUE,
    role varchar(10) not null,
    password varchar(255) not null
);