spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Miyakerin/config-server.git
          clone-on-start: true
          search-paths:
            - "{application}"
            - ""
